import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import { Inter } from "@next/font/google";

import "./globals.css";
import Header from "./components/layouts/Header";
import Favicon from "/public/favicon.ico";

// Googleフォントを適用（デフォルト設定）
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <body className={inter.className}>
        {/* ヘッダー */}
        <Header />
        {children}
      </body>
    </html>
  );
}
