import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import { Inter } from "@next/font/google";

import "./globals.css";
import Header from "./components/layouts/Header";

// Googleフォントを適用（デフォルト設定）
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ヘッダー */}
        <Header />
        {children}
      </body>
    </html>
  );
}
